src/main/java/com/genigraph/library/model/Book.java
package com.genigraph.library.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.Pattern;

import lombok.Data;

@Data
@Entity
public class Book {
	@Id
	@GeneratedValue
	private Long id;
	private String title;
	@Pattern(regexp = "[a-zA-Z][a-zA-Z-. ]*", message = "The name must start with a letter.")
	private String author;
	private String url;
	private String img;
	private String editor;
	private boolean available;
}

src/main/java/com/genigraph/library/jsf/BookBean.java
package com.genigraph.library.jsf;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import lombok.Data;

import com.genigraph.library.model.Book;
import com.genigraph.library.rest.BookService;

@Data
@Named
@SessionScoped
public class BookBean implements Serializable {
	private static final long serialVersionUID = 1L;

	@Inject
	private BookService service;
	private Book book = new Book();

	public String save() {
		service.create(book);
		book = new Book();
		return null;
	}
	
	public List<Book> getBooks() {
		return service.getAll();
	}
}

src/main/webapp/chat.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition template="template/template.xhtml">
		<ui:define name="content">
			<h1>WebSocket : Chat</h1>
			<div style="text-align: center;">
				<form action="">
					<table>
						<tr>
							<td>Users<br />
								<textarea readonly="readonly" rows="6" cols="20" id="userField">
								</textarea>
							</td>
							<td>Chat Log<br />
								<textarea readonly="readonly" rows="6" cols="50" id="chatlogField">
								</textarea>
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<input id="textField" name="name" value="Genigraph" type="text" /><br />
								<input onclick="join();" value="Join" type="button" />
								<input onclick="send_message();" value="Chat" type="button" />
							</td>
						</tr>
					</table>
				</form>
			</div>
			<div id="output"></div>
			<script language="javascript" type="text/javascript" src="resources/js/websocket.js"></script>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition template="template/template.xhtml">
		<ui:define name="content">
			<h1>Hello World ${1+1}!</h1>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">
<h:body>
	<ui:composition template="template/template.xhtml">
		<ui:define name="content">
			<h1>Books list</h1>
			<h:dataTable value="${bookBean.books}" var="b">
				<h:column>
					<f:facet name="header">Title</f:facet>
					<a href="#{b.url}">${b.title}</a>
				</h:column>
				<h:column>
					<f:facet name="header">Author</f:facet>
					${b.author}
				</h:column>
				<h:column>
					<f:facet name="header">Editor</f:facet>
					${b.editor}
				</h:column>
				<h:column>
					<f:facet name="header">Available</f:facet>
					<h:selectBooleanCheckbox value="${b.available}" />
				</h:column>
			</h:dataTable>

			<h1>Add a new book</h1>
			<h:form>
				<h:panelGrid columns="3">
					Title :
					<h:inputText id="title" value="#{bookBean.book.title}" />
					<h:message for="title" />
					Author :
					<h:inputText id="author" value="#{bookBean.book.author}" />
					<h:message for="author" />
					Url :
					<h:inputText id="url" value="#{bookBean.book.url}" />
					<h:message for="url" />
					Img :
					<h:inputText id="img" value="#{bookBean.book.img}" />
					<h:message for="img" />
					Editor :
					<h:inputText id="editor" value="#{bookBean.book.editor}" />
					<h:message for="editor" />
					Available :
					<h:selectBooleanCheckbox id="available" value="#{bookBean.book.available}" />
					<h:message for="available" />
				</h:panelGrid>

				<h:commandButton type="submit" value="Submit"
					action="#{bookBean.save}" />
				<h:commandButton type="reset" value="Reset"></h:commandButton>

			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/template/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
	<h:outputStylesheet name="style.css" library="css" />
</h:head>

<h:body>
	<div id="page">
		<div id="header">
			<img src="#{resource['images:logo.png']}" alt="Genigraph" />
			Library
		</div>

		<div id="content">
			<ui:insert name="content" />
		</div>

		<div id="footer">
			<!-- TODO -->
		</div>

	</div>

</h:body>
</html>